# Generated by Django 3.1.7 on 2021-02-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caryear', models.PositiveSmallIntegerField()),
                ('carmake', models.CharField(max_length=100)),
                ('offertype', models.CharField(max_length=100)),
                ('offerstartdate', models.DateField()),
                ('offerenddate', models.DateField()),
                ('offerdetailsummary', models.CharField(max_length=100)),
                ('offerdetaildetails', models.CharField(max_length=10000, null=True)),
                ('offeristackable', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caryear', models.PositiveSmallIntegerField()),
                ('carmake', models.CharField(max_length=100)),
                ('carmodel', models.CharField(max_length=100)),
                ('cartrim', models.CharField(max_length=100)),
                ('offertype', models.CharField(max_length=100)),
                ('offerstartdate', models.DateField()),
                ('offerenddate', models.DateField()),
                ('offerdetailsummary', models.CharField(max_length=100)),
                ('offerdetaildetails', models.CharField(max_length=10000, null=True)),
                ('offeristackable', models.BooleanField(null=True)),
            ],
        ),
    ]
