# Generated by Django 3.1.7 on 2021-03-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cashdealincentive',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='financeduration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='financerate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='leasedownpayment',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='leaseduration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='leasepayment',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='leaserate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offeranddeal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerplusdeal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
