# Generated by Django 3.1.7 on 2021-03-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_carmake_carmodel_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year',
            new_name='CarYear',
        ),
    ]
