# Generated by Django 3.1.7 on 2021-04-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210418_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerdetailsummary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
