# Generated by Django 3.1.7 on 2021-10-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20210418_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandoffer',
            name='offermonth',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='cartype',
            field=models.CharField(default='Sedan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='caryear',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offermonth',
            field=models.TextField(null=True),
        ),
    ]
