# Generated by Django 3.1.7 on 2021-10-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20211013_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='caryear',
        ),
    ]
