# Generated by Django 3.1.7 on 2021-03-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20210302_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmsrp', models.FloatField()),
                ('paidpretax', models.FloatField()),
                ('paidoutthedoor', models.FloatField()),
                ('comments', models.CharField(max_length=3000)),
                ('carmake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.carmake')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.carmodel')),
                ('caryear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.caryear')),
            ],
        ),
    ]
