# Generated by Django 3.1.7 on 2021-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_whatipaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerlocation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='cartrim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerdetailsummary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
