# Generated by Django 3.1.7 on 2021-10-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20211013_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='carmake',
            field=models.CharField(max_length=100),
        ),
    ]
